language: objective-c
branches:
  only:
    - master
    - release
    - travis
before_install:
  - (ruby --version)
  - sudo motion update
gemfile:
  - Gemfile
script:
  - bundle install --jobs=3 --retry=3
  - bundle exec rake clean
  - bundle exec rake spec
